### ISSUE TITLE
"log-router" is not written in  "Application name"

### ISSUE THREAD

**Issue by takasou777** [ibm-cloud-docs/cloud-logs#1]
Hello, 

"log-router" is also shown in "Application name" but is not written at docs.
please modify docs.
![image (54)](https://github.com/ibm-cloud-docs/cloud-logs/assets/122076523/206de331-2117-4a82-bce3-cc08fc55d8f4)

Thanks,

**Comment by vanadiscrawford** [comment]
Thank you for your comment.  This was an error at the time the issue was opened and has subsequently been resolved.
