### ISSUE TITLE
metadata tag not rendering in docs

### ISSUE THREAD

**Issue by ocofaigh** [ibm-cloud-docs/cloud-logs#3]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/cloud-logs?topic=cloud-logs-getting-started

### What do you think needs to be updated?

The tag `{{site.data.keyword.atracker_notm}}` is not rendering to a valid text string in the docs:

![image](https://github.com/user-attachments/assets/24f76576-e388-4951-a2a5-ebb287c55029)

**Comment by vanadiscrawford** [comment]
Thank you for your comment.  This error is being fixed.
