### ISSUE TITLE
Provide instructions detailing how to import a dashboard from a file

### ISSUE THREAD

**Issue by donbourne** [ibm-cloud-docs/cloud-logs#4]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/cloud-logs?topic=cloud-logs-about_dashboards

### What do you think needs to be updated?

If user has been given a file which contains the dashboard, they may want instructions on how to import that dashboard so that they can use it.

**Comment by lopezdsr** [comment]
Thank you very much for your feedback. Documentation will be added showing how to export and imprt dashboard between instances.
